"""
Django settings for category_service.

Generated by 'django-admin startproject' using Django 5.0.6, then trimmed
for a JSON-API microservice: admin/sessions/messages/templates removed.
Configuration is environment-variable driven (see .env.example).
"""
import os
from pathlib import Path

from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# --- Core --------------------------------------------------------------------
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "insecure-dev-key-change-me")
DEBUG = os.environ.get("DJANGO_DEBUG", "False").lower() == "true"
ALLOWED_HOSTS = [h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "*").split(",")]

# --- Apps --------------------------------------------------------------------
# Read-only JSON microservice: no admin, no auth, no sessions, no messages,
# no templates. Only what's strictly needed to serve a JSON API and a
# healthz endpoint.
INSTALLED_APPS = [
    "django.contrib.contenttypes",
    "django.contrib.staticfiles",
    "rest_framework",
    "categories",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.common.CommonMiddleware",
]

ROOT_URLCONF = "category_service.urls"
WSGI_APPLICATION = "category_service.wsgi.application"

# --- Database ----------------------------------------------------------------
# In production: docker-compose sets POSTGRES_HOST to "category-db".
# In local dev with venv: point POSTGRES_HOST to "localhost" (running a local
# Postgres) or to the docker-compose service hostname if you started it.
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "category_db"),
        "USER": os.environ.get("POSTGRES_USER", "category_user"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", ""),
        "HOST": os.environ.get("POSTGRES_HOST", "category-db"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        "CONN_MAX_AGE": 60,
    }
}

# --- I18N --------------------------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# --- Static (no HTML, kept only because INSTALLED_APPS needs staticfiles) ---
STATIC_URL = "static/"

# --- DRF ---------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
    "DEFAULT_PARSER_CLASSES": ["rest_framework.parsers.JSONParser"],
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.AllowAny"],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    # django.contrib.auth is intentionally NOT in INSTALLED_APPS, so DRF's
    # default AnonymousUser / Token fallbacks would crash every request.
    # Setting these to None tells DRF to skip the lazy import entirely.
    "UNAUTHENTICATED_USER": None,
    "UNAUTHENTICATED_TOKEN": None,
}

# --- Default PK --------------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
